### ISSUE TITLE
Mburger webcomponent doesn't work if menu is cloned

### ISSUE THREAD

**Issue by d13creative** [FrDH/mmenu-js#1313]
mmenu version 9.2
mburger-webcomponent version 3.1.1

Not sure if the issue is down to mmenu or mburger so apologies if I've posted in the wrong place.

In this example (copied from your tutorial) a standard link will open the menu but the web component doesn't.

If I remove `clone: true` from the script then the web component works but obviously doesn't clone the menu.

`<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width minimum-scale=1.0 maximum-scale=1.0 user-scalable=no" />
        <title>My webpage</title>
        <script src="/js/mburger/index.js" type="module"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/9.2.0/mmenu.min.css" integrity="sha512-nNatP1G6CEh43irXY/GN4cDcLRX/R0jAYAV/ulFZcotSXcuIQE5Do4TuDOYNAD2SCIpmIbaYSllyjTysSCkpEw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <style>
            #page {
                background-color: #fff;
            }
            mm-burger {
                --mb-bar-height: 2px;
        
                padding: 5px;
                border: 1px solid;
                border-radius: 5px;
            }
        </style>
    </head>
    <body>
        <div id="page">
            <div id="header">
                <mm-burger
                    menu="menu"
                    fx="collapse"
                    ease="elastic"
                    role="button"
                    tabindex="0"
                    title="Open the menu"
                >
                    Menu
                </mm-burger>
                <a href="#menu">
                    This works
                </a>
                <nav id="menu">
                    <ul>
                        <li><a href="/">Home</a></li>
                        <li><span>About us</span>
                            <ul>
                                <li><a href="/about/history/">History</a></li>
                                <li"><a href="/about/team/">The team</a></li>
                                <li><a href="/about/address/">Our address</a></li>
                            </ul>
                        </li>
                        <li><a href="/contact/">Contact</a></li>
                    </ul>
                </nav>
            </div>
            <div id="content">
                <h1>Page title</h1>
                <p>Some content.</p>
            </div>
        </div><script src="https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/9.2.0/mmenu.js" integrity="sha512-qxFojA1Tj+vpMCTq+OKdmLvANffypm+ITLJ5GfWnCBD3UADtCWQb+2SDHOaL+1i0GVJYZQ4IQFggCm14YUaEBw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script>
            document.addEventListener(
                "DOMContentLoaded", () => {
                    new Mmenu( "#menu", {
                        // options
                    
                    }, {
                        // configuration
                        offCanvas: {
                            clone: true
                        }
                    } );
                }
            );
        </script>
    </body>
</html>`

**Comment by FrDH** [comment]
Good point 🤔 
I rarely test the clone option and mburger probably doesn't catch up on it.

I'll have a look at it later on

**Comment by FrDH** [comment]
should be fixed in 3.1.2

**Comment by d13creative** [comment]
Thanks for the update but I don't think it has been fixed. Not that I understand much but I set a breakpoint at the point of code that you modified.  `menuNode.matches('.mm-menu')` doesn't find the cloned menu because it doesn't exist in the DOM at the moment this code is called so the menus can't be connected.🤷‍♂️

**Comment by FrDH** [comment]
Could you give 3.1.3 a try?

**Comment by d13creative** [comment]
No, still doesn't work,`connectMenu` never gets called. I changed `#mm-${newValue}` to `#mm-cloned-${newValue}` to see what happens and this then called the `connectMenu` function but nothing happens when you click on the hamburger.

**Comment by FrDH** [comment]
My bad, try 3.1.4
Sorry for the trouble on this, should not have been this much of a problem.

**Comment by d13creative** [comment]
Me again! No worries, thanks for your help. Now getting this error when clicking on the burger `index.js:56 Uncaught TypeError: Cannot read properties of undefined (reading 'open')
    at index.js:56:192
    at default.toggle (index.js:112:17)`

Debugging shows that the mmApi is missing when the toggle function is called causing the error

<img width="845" alt="Screenshot 2022-12-27 at 17 07 58" src="https://user-images.githubusercontent.com/1433528/209699337-14f7a532-776e-4e18-b9f3-c2fc8798391f.png">
<img width="1026" alt="Screenshot 2022-12-27 at 17 10 24" src="https://user-images.githubusercontent.com/1433528/209699362-13223925-47e9-4cc2-8deb-1781346b9197.png">

At least we're getting further along!😆

**Comment by FrDH** [comment]
Well, apparently there was an issue in the mmenu.js plugin binding the API to the original node...
If you can update the mmenu.js plugin to version 9.3, all should be fixed.

**Comment by d13creative** [comment]
Perfect! Many thanks!
